### PR TITLE
Feature/close button alignment

### PR DESCRIPTION
**Pull request by OneXeor**
Ability to set alignment for the close button via alignment enum or just remove it

### CODE REVIEW

**Comment by Jake-Short** [comment]
Looks good so far, one issue I'm running into is that ".none" simply places the x right in the middle of the image, and does not make it disappear (should it disappear with ".none", or did you intend for that to mean it just aligns itself in the middle?). Also, README will need an update for this updated functionality (I can add this too). It's a breaking change so it will bump up the version to 3.0.0.

For reference, this is the code snippet I used:
```swift
ImageViewer(image: .constant(Image(uiImage: UIImage(named: "testimage.jpg")!)), viewerShown: self.$isShown, closeButtonAlignment: .none)
```

**Comment by OneXeor** [comment]
@Jake-Short Sorry, I've checked and I couldn't reproduce it, It work's fine for me (xmark is removed), maybe you have tested not the last version? More over this checking as you can see, have to prevent xmark appearing
Screenshot 2021-06-27 at 19 05 57

**Comment by Jake-Short** [comment]
@OneXeor It looks like the issue was that I needed to explicitly use CloseButtonAlignment.none, rather than just .none. The changes look good, I'll update the README and get this merged.

**Comment by Jake-Short** [comment]
Merged this into the master-dev branch. I will publish it alongside v3.0.0 along with some other changes. There is a pre-release version of 3.0.0 that I just published which includes this close button change.

**Pull request merged**
